### ISSUE TITLE
Microsoft Azure Dev Tools for Teachingの追加の提案

### ISSUE THREAD

**Issue by Suree33** [Make-IT-TSUKUBA/awesome-tsukuba#15]
筑波大生なら、 Microsoft Azure Dev Tools for Teaching を使用することでWindows OS（Education版）やVisual Studio Enterpriseなどのライセンスを入手することができます。他にも、Azureの100ドル分のクレジットを無料でもらうことができる特典もあります。

[Microsoft Azure Dev Tools for Teaching (旧Microsoft Imagine Standard) | 筑波大学 情報環境機構 学術情報メディアセンター](https://www.cc.tsukuba.ac.jp/wp/service/sl/ees/microsoft_azuredevtools/)

ただし、当然ながら営利目的などには使用できないという規定があるようです。
（以下、上記ウェブページより引用）
> Azure Dev Tools のソフトウェアの使用は教育・研究目的に限定されており、次のような制限があります。
> - 営利目的での開発はできません。
> - 学群/研究室の計算機環境のインフラ構築には利用できません。例えば、Exchange Server を研究室のメールサーバとして実運用することはできません。

**Comment by onokatio** [comment]
@Suree33 ありがとうございます！PR出していただけますか？
