### ISSUE TITLE
分類がわかりにくい

### ISSUE THREAD

**Issue by onokatio** [Make-IT-TSUKUBA/awesome-tsukuba#6]
いいアイデアないだろうか

**Comment by eniehack** [comment]
以下の順序で分類するのはどうでしょうか

まずは以下のように分類する:
1. 公式の情報源、ツールか否か？公式のものでなければ2へ
2. twinsやKdBなどサービスに関連するもので分類、できない場合は3へ
3. 「履修スケジュール確認」などのシチュエーション別の分類、できない場合は4へ
4. 「その他」として分類

次に、上の基準で分類されたグループ内を形態ごとに分類する
e.g. 
- 「履修スケジュール確認」→スマホアプリ→twin:te
- KdB→Webサイト→KdBもどき

**Comment by onokatio** [comment]
@eniehack その階層方式とてもいい気がします。
お手隙の際にPR出してもらったりなどできますか？

**Comment by eniehack** [comment]
了解です！
